version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "23:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 25
    target-branch: main
    assignees:
      - mprins
    labels:
      - infrastructure
      - dependency

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: thursday
      time: "23:00"
      timezone: Europe/Amsterdam
    assignees:
      - mprins
    labels:
      - infrastructure
