# use eg. `mvn test -Dlogging-profile=verbose-logging` to apply this configuration
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
handlers=java.util.logging.ConsoleHandler

.level=INFO
org.geotools.data.level=FINE
#org.tailormap.api.geotools.data.excel.level=ALL
org.tailormap.api.geotools.data.excel.level=FINE